import { Router } from 'express';
import usersRouter from './users';
import jobsRouter from './jobs';
import commissionsRouter from './commissions';
import paymentsRouter from './payments';
import subscriptionsRouter from './subscriptions';
import reviewsRouter from './reviews';
import announcementsRouter from './announcements';
import analyticsRouter from './analytics';
import settingsRouter from './settings';
import audit-logRouter from './audit-log';
const router = Router();
router.use('/users', usersRouter);
router.use('/jobs', jobsRouter);
router.use('/commissions', commissionsRouter);
router.use('/payments', paymentsRouter);
router.use('/subscriptions', subscriptionsRouter);
router.use('/reviews', reviewsRouter);
router.use('/announcements', announcementsRouter);
router.use('/analytics', analyticsRouter);
router.use('/settings', settingsRouter);
router.use('/audit-log', audit-logRouter);
export default router;
